<?php
/** @var Alevelmod\Learning\Block\Post $block*/
?>

<?php foreach ($block->getPost()->getItems() as $item): ?>
    <span>Name: <?= $item->getName();?></span><br/>
    <span>Surname: <?= $item->getSurname();?></span><br/>
    <span>Email: <?= $item->getEmail();?></span><br/>
    <span>Content: <?= $item->getContent();?></span>
    <span>Age: <?= $item->getAge();?></span>
------------------------------------------------------
<?php endforeach; ?>